version: "3.9"
services:
  energy-mvc:
<<<<<<< HEAD
    image: erikrasniqi/energy-mvc:latest
=======
    image: allredmatt/energy-mvc:latest
>>>>>>> fcb0bab4d63dafc3dd8bf2ffa08d3ba18b7312ec
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - energy-db
      - energy-python
    networks:
      - energy-network
  energy-db:
    image: erikrasniqi/energy-db:latest
    ports:
      - "5432:5432"
    restart: always
    networks:
      - energy-network
  energy-python:
    image: erikrasniqi/energy-python:latest
    ports:
      - "3014:3014"
    restart: always
    networks:
      - energy-network
networks:
  energy-network:
