version: "3.9"
services:
  energy-mvc:
    image: allredmatt/energy-mvc:latest
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - energy-db
      - energy-python
    networks:
      - energy-network
  energy-db:
    image: allredmatt/energy-db:latest
    ports:
      - "5432:5432"
    restart: always
    networks:
      - energy-network
  energy-python:
    image: giorgia825/energy-python:latest
    ports:
      - "3001:3001"
    restart: always
    networks:
      - energy-network
networks:
  energy-network:
